### ISSUE TITLE
Password requirements?

### ISSUE THREAD

**Issue by nickbasis** [donniedarkoparko/app#42]
**Enhancement**

Are there any password requirements? 
At the moment it seems like I could use a 3 letter password like 'abc'. 

_For example:_

**Password Requirements**
_Between 8 and 30 characters in length.
Must contain at least one letter and one number.
Cannot use repeating characters (e.g. aaa64135, 111bcxjk)_

And other crap like that...

**Comment by donniedarkoparko** [comment]
Currently the only requirements on passwords is a minimum of 6 characters. Otherwise an instruction should appear and not let you proceed. 6 is the bear minimum that firebase allows. I'm not sure what their max is though, i'll look into it.

**Comment by donniedarkoparko** [comment]
done
